### ISSUE TITLE
[P3B-3] Shopping list information

### ISSUE THREAD

**Issue by allenpoon** [ierg4210/shop67#1]
Your shopping list is store on localStorage with following data:
{pid, prod_name, number, price}

By requirement, it should

store {pid, number}
request {prod_name, price} from AJAX

![image](https://cloud.githubusercontent.com/assets/3294681/7520220/b8a8faa6-f517-11e4-8236-c84936dbf33b.png)

Users may change the localStorage so that users can buy products to be cheapest

It expected to change back to a normal product information by sending request to server

When product is updated, the shopping list would not updated. This will be misleading the client and do the wrong decision. Or you send the whole things to server and server does not check the relation of the product, it will receive an unexpected total from the client.

prossible fix: you should request the server each time when loading shopping cart in page reload and do not trust the {pid, price} relation sent from client

**Comment by hkop2002** [comment]
[TA comment] According to Phase 3B, we don't always need to check the correctness of shopping cart items in local storage, unless you press the checkout button and submit to paypal. As long as the item and price list in paypal is correct (can handle both wrong PID and price), I don't think it's an issue.

**Comment by allenpoon** [comment]
But in previous commit e4d054d7fcd2696e9be094e2d9e2b653c67edfe6 , it will mischarge user if user change the localStorage and checkout process have no check the price and relied on localStorage data. Is it still not an issue?
